# You will need to unzip pima-indians-diabetes-database.zip for this code to work

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#The-model:" data-toc-modified-id="The-model:-0.0.1"><span class="toc-item-num">0.0.1&nbsp;&nbsp;</span>The model:</a></span></li><li><span><a href="#Log-likelihood-of-the-data-(b/c-X-is-assumed-iid):" data-toc-modified-id="Log-likelihood-of-the-data-(b/c-X-is-assumed-iid):-0.0.2"><span class="toc-item-num">0.0.2&nbsp;&nbsp;</span>Log-likelihood of the data (b/c X is assumed iid):</a></span></li><li><span><a href="#So-maximizing-this-gives-us-the-maximum-likelihood-estimates-for-our-parameters.-We-can-do-so-by-(unsurprisingly)-taking-the-partial-derivative-w/-respect-to-each-parameter,-set-it-equal-to-0,-and-solve-the-equation.-Reference:-http://web.engr.oregonstate.edu/~xfern/classes/cs534/notes/LDA.pdf" data-toc-modified-id="So-maximizing-this-gives-us-the-maximum-likelihood-estimates-for-our-parameters.-We-can-do-so-by-(unsurprisingly)-taking-the-partial-derivative-w/-respect-to-each-parameter,-set-it-equal-to-0,-and-solve-the-equation.-Reference:-http://web.engr.oregonstate.edu/~xfern/classes/cs534/notes/LDA.pdf-0.0.3"><span class="toc-item-num">0.0.3&nbsp;&nbsp;</span>So maximizing this gives us the maximum likelihood estimates for our parameters. We can do so by (unsurprisingly) taking the partial derivative w/ respect to each parameter, set it equal to 0, and solve the equation. Reference: <a href="http://web.engr.oregonstate.edu/~xfern/classes/cs534/notes/LDA.pdf" target="_blank">http://web.engr.oregonstate.edu/~xfern/classes/cs534/notes/LDA.pdf</a></a></span></li><li><span><a href="#Using-these-parameter-estimates,-we-can-model-$p(y\mid-x)$,-the-posterior-distribution,-using-Bayes's-rule:" data-toc-modified-id="Using-these-parameter-estimates,-we-can-model-$p(y\mid-x)$,-the-posterior-distribution,-using-Bayes's-rule:-0.0.4"><span class="toc-item-num">0.0.4&nbsp;&nbsp;</span>Using these parameter estimates, we can model $p(y\mid x)$, the posterior distribution, using Bayes's rule:</a></span></li><li><span><a href="#Since-are-classification-strategy-will-involve-choosing-the-class-that-is-most-probable,-we-do-not-need-to-calculate-the-denominator-of-Bayes's-rule-because-it-is-independent-of-y" data-toc-modified-id="Since-are-classification-strategy-will-involve-choosing-the-class-that-is-most-probable,-we-do-not-need-to-calculate-the-denominator-of-Bayes's-rule-because-it-is-independent-of-y-0.0.5"><span class="toc-item-num">0.0.5&nbsp;&nbsp;</span>Since are classification strategy will involve choosing the class that is most probable, we do not need to calculate the denominator of Bayes's rule because it is independent of y</a></span></li><li><span><a href="#However-it-is-good-to-know-that-the-denominator-is-given-by:" data-toc-modified-id="However-it-is-good-to-know-that-the-denominator-is-given-by:-0.0.6"><span class="toc-item-num">0.0.6&nbsp;&nbsp;</span>However it is good to know that the denominator is given by:</a></span></li><li><span><a href="#Finally,-the-other-(actually-imporant)-quantities-in-Bayes's-rule-are-given-by-our-model-(i.e.-we-assumed-X-is-distributed-Gaussian-and-Y-is-Bernoulli)" data-toc-modified-id="Finally,-the-other-(actually-imporant)-quantities-in-Bayes's-rule-are-given-by-our-model-(i.e.-we-assumed-X-is-distributed-Gaussian-and-Y-is-Bernoulli)-0.0.7"><span class="toc-item-num">0.0.7&nbsp;&nbsp;</span>Finally, the other (actually imporant) quantities in Bayes's rule are given by our model (i.e. we assumed X is distributed Gaussian and Y is Bernoulli)</a></span></li><li><span><a href="#So-let's-implement-this-:)" data-toc-modified-id="So-let's-implement-this-:)-0.0.8"><span class="toc-item-num">0.0.8&nbsp;&nbsp;</span>So let's implement this :)</a></span></li><li><span><a href="#Maximum-likelihood-estimates-for-each-parameter:" data-toc-modified-id="Maximum-likelihood-estimates-for-each-parameter:-0.0.9"><span class="toc-item-num">0.0.9&nbsp;&nbsp;</span>Maximum likelihood estimates for each parameter:</a></span></li><li><span><a href="#Heart-Disease-data-set-from-Kaggle:-https://www.kaggle.com/uciml/pima-indians-diabetes-database/data" data-toc-modified-id="Heart-Disease-data-set-from-Kaggle:-https://www.kaggle.com/uciml/pima-indians-diabetes-database/data-0.0.10"><span class="toc-item-num">0.0.10&nbsp;&nbsp;</span>Heart Disease data set from Kaggle: <a href="https://www.kaggle.com/uciml/pima-indians-diabetes-database/data" target="_blank">https://www.kaggle.com/uciml/pima-indians-diabetes-database/data</a></a></span></li></ul></li></ul></li></ul></div>

### The model:

$$ y \sim Bernoulli(\phi)$$
$$ x \mid y = 0 \sim \mathcal{N}(\mu_0, \Sigma)$$
$$ x \mid y = 1 \sim \mathcal{N}(\mu_1, \Sigma)$$
<br>
Notice that each Gaussian has the same covariance matrix $\Sigma$. This is an additional simplifying homoscedasticity assumption of GDA (which is the same as LDA). This differs from Quadratic Discriminant Analysis which does not use this assumptions, implying that there is different covariance matrices for each Gaussian. See https://en.wikipedia.org/wiki/Linear_discriminant_analysis#LDA_for_two_classes

### Log-likelihood of the data (b/c X is assumed iid):

$$ \mathcal{L}(\phi, \mu_0, \mu_1, \Sigma) = \log\prod_{i=1}^m p(x^{(i)} \mid y^{(i)}; \mu_0, \mu_1, \Sigma)p(y^{(i)};\phi) $$

### So maximizing this gives us the maximum likelihood estimates for our parameters. We can do so by (unsurprisingly) taking the partial derivative w/ respect to each parameter, set it equal to 0, and solve the equation. Reference: http://web.engr.oregonstate.edu/~xfern/classes/cs534/notes/LDA.pdf

### Using these parameter estimates, we can model $p(y\mid x)$, the posterior distribution, using Bayes's rule:

$$ p(y \mid x) = \frac{p(x \mid y)p(y)}{p(x)} $$

### Since are classification strategy will involve choosing the class that is most probable, we do not need to calculate the denominator of Bayes's rule because it is independent of y
$$
\begin{align*}
  \underset{y}{\mathrm{argmax}}p(y \mid x) &= \underset{y}{\mathrm{argmax}} \frac{p(x \mid y) p(y)}{p(x)} \\
 &= \underset{y}{\mathrm{argmax}}p(x \mid y)p(y)
\end{align*}
$$

### However it is good to know that the denominator is given by:

$$ p(x) = \sum_{k=1}^{C} p(x \mid y = k)p(y = k) $$
, where $C$ is the number of classes. The quantities in the summation are given by our model. 

### Finally, the other (actually imporant) quantities in Bayes's rule are given by our model (i.e. we assumed X is distributed Gaussian and Y is Bernoulli)

$$ p(y) = \phi^y(1 - \phi)^{(1-y)} $$
<br>
$$ p(x \mid y = k) = \dfrac{1}{(2\pi)^{n/2} \mid \Sigma \mid^{1/2}} \exp\Big(-\frac12 (x-\mu_k)^T \Sigma^{-1}(x -
\mu_k)\Big)$$
<br>
Note that $k \in \{0,1\} $ because $Y$ is a binary variable in our specific problem.

### So let's implement this :)

### Maximum likelihood estimates for each parameter:

$$ \phi = \frac{1}{m} \sum_{i=1}^m 1\{y^{(i)} = 1\} $$
This is just the fraction of positive class examples (for example, the number of emails that are spam).
$$ \mu_0 = \frac{\sum_{i=1}^m 1\{y^{(i)} = 0\}x^{(i)}}{\sum_{i=1}^m 1\{y^{(i)} = 0\}} $$ 
<br>
$$ \mu_1 = \frac{\sum_{i=1}^m 1\{y^{(i)} = 1\}x^{(i)}}{\sum_{i=1}^m 1\{y^{(i)} = 1\}} $$ 
or more generally,
$$ \mu_k = \frac{\sum_{i=1}^m 1\{y^{(i)} = k\}x^{(i)}}{\sum_{i=1}^m 1\{y^{(i)} = k\}} $$ 
, for non-binary classification problems. Essentially, each of these formulas are saying to sum each example $x^{(i)}$ (which may be a vector) with class $y^{(i)} = k$ and average it over all examples with $y^{(i)} = k$.
$$ \Sigma = \frac{1}{m} \sum_{i=1}^m (x^{(i)} - \mu_{y^{(i)}})(x^{(i)} - \mu_{y^{(i)}})^{T}$$ 
This is the covariance matrix for the multivariate gaussian, which is a generalization of the variance of a real-valued random variable.

In [129]:
import sklearn as sk, sklearn.model_selection
import pandas as pd

diabetes = pd.read_csv('diabetes.csv')
Y = diabetes['Outcome']
X = diabetes.drop(['Outcome'], axis=1)
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X, Y, 
                                    test_size=0.33, 
                                    random_state=42)

def my_covariance_matrix(X):
    '''
        Computes the covariance of X
        X: array-like, shape = (n_samples, n_features)
        Returns:
            Covariance matrix of X, shape = (n_features, n_features)
    '''
    n_samples = X.shape[0]
    X = X.T
    avg = np.average(X, axis=1)
    X = X.astype(np.float64)
    X -= avg[:, np.newaxis]
    return np.dot(X, X.T) / np.float64(n_samples)

X = np.array([[-1, -5, 3], 
              [-2, -1, 5], 
              [-3, -2, 4], 
              [13, 1, -13], 
              [2, 1, 3], 
              [3, 2, 5]])
y = np.array([1, 1, 1, 2, 2, 2])
my_covariance_matrix(X)

array([[ 28.66666667,   7.        , -31.16666667],
       [  7.        ,   5.55555556,  -3.88888889],
       [-31.16666667,  -3.88888889,  40.80555556]])

In [55]:
import numpy as np
import pandas as pd 
import sklearn as sk, sklearn.model_selection
import seaborn as sns
import matplotlib.pyplot as plt

class BinaryGDA():
    
    def __init(self):
        pass
    
    def fit(self, X_train, y_train):
        if isinstance(X_train, pd.DataFrame):
            X_train = X_train.values
        elif isinstance(X_train, list):
            X_train = np.array(X_train)
        #else:
        #    raise ValueError('X_train should be 2d array or DataFrame')
        if isinstance(y_train, pd.Series):
            y_train = y_train.values
        elif isinstance(y_train, list):
            y_train = np.array(y_train)
        #else:
        #    raise ValueError('y_train should be 1d array')
        self.phi = self.compute_phi(y_train)
        self.mu = self.compute_mu(X_train, y_train)
        self.covariance = self.compute_covariance(X_train, y_train)
        
    def predict_bayes(self, X_test):
        # Compute argmax{c_k} p(x | c_k) * p(c_k) / [sum(p(x | c_k) * p(c_k)) over classes]
        
        pass
    
    def class_conditional_p(self, c_k, x):
        '''
            Computes the class conditional probability p(x | c_k)
            i.e. the mulitvariate gaussian equation with shared covariance
            matrix and mu_k
            c_k: the class to compute the probability from
            x: the test x to compute from
        '''
        # the dimension of the gaussians
        d = len(self.covariance)
        pi_constant = (2 * np.pi) ** (1.0 / d)
        covariance_constant = \
            np.linalg.det(self.covariance) ** (0.5)
        constant =  1.0 / pi_constant * covariance_constant
        
        left = -0.5 * (x - self.mu[c_k]).T
        middle = np.linalg.inv(self.covariance)
        right = (x - self.mu[c_k])
        exponent = np.exp(left * middle * right)
        
            
    
    def print_params(self):
        #if self.phi == None or self.covariance  == None or self.mu == None:
            #raise ValueError('You must fit the model first')
        print('phi', self.phi)
        print('mu', self.mu)
        print('covariance matrix', self.covariance)
    
    def compute_mu(self, X_train, y_train):
        '''
        Computes the average feature vector for every class
        X_train: 
            2d np array where rows are examples and columns are features,
            all of which should be quantitative
        y_train: 
            1d np array representing labels in [0, 1]
        '''
        classes = np.unique(y_train)
        mu = []
        for c in classes:
            mu.append((y_train == c).dot(X_train) / np.sum(y_train == c))
        return mu
    
    def compute_phi(self, y_train):
        '''
        Computes the proportion of "success" valued examples
        y_train: 
            1d np array representing labels in [0, 1]
        '''
        num_examples = len(y_train)
        classes = np.unique(y_train)
        phi = []
        for j in classes:
            phi.append(np.sum(y_train == j) / num_examples)
        return phi
    
    def compute_covariance(self, X_train, y_train):
        '''
        Computes the shared covariance matrix of the Gaussians fit to the data
        i.e. it computes the pooled within-class covariance matrix used for each Gaussian
        X_train: 
            2d np array where rows are examples and columns are features,
            all of which should be quantitative
        y_train: 
            1d np array representing labels in [0, 1]
        '''
        num_examples = len(y_train)
        classes = np.unique(y_train)
        # covariance = np.zeros((X_train.shape[1],X_train.shape[1]))
        covs = []
        for group in classes:
            Xg = X_train[y_train == group, :]
            # covs.append(np.atleast_2d(covariance.empirical_covariance(Xg)))
            covs.append(np.atleast_2d(my_covariance_matrix(Xg)))
        '''
        for group in classes:
            Xg = X[y == group, :]
            covs.append(np.atleast_2d(_cov(Xg, shrinkage)))
        return np.average(covs, axis=0, weights=priors)
        for c in classes:
            for i in range(num_examples):
                if y_train[i] == c:
                    covariance = np.outer(X_train[i] - self.mu[c], 
                             (X_train[i] - self.mu[c]).T)
        '''
        return np.average(covs, axis=0)
        # return co / (num_examples - len(classes))

bgda = BinaryGDA()
bgda.fit(X_train, y_train)
mu = bgda.compute_mu(X_train.values, y_train.values)
bgda.compute_covariance(X_train.values, y_train.values)
# c = bgda.compute_covariance(X_train.values, y_train.values)
# np.linalg.inv(c)

ValueError: operands could not be broadcast together with shapes (332,332) (182,182) 

In [5]:
from sklearn import covariance
covariance.empirical_covariance(X_train)

array([[ 1.07190571e+01,  1.40955654e+01,  9.45769807e+00,
        -3.14040334e+00, -2.01058684e+01,  8.61911611e-01,
        -2.02742736e-02,  2.07322064e+01],
       [ 1.40955654e+01,  1.04503706e+03,  1.00831451e+02,
         1.11968009e+01,  1.30806211e+03,  4.90694235e+01,
         1.97178482e+00,  1.01251011e+02],
       [ 9.45769807e+00,  1.00831451e+02,  3.23684583e+02,
         4.46035065e+01,  1.09750776e+02,  3.54084801e+01,
         3.22380770e-01,  5.29893488e+01],
       [-3.14040334e+00,  1.11968009e+01,  4.46035065e+01,
         2.39829127e+02,  7.40715787e+02,  4.51210934e+01,
         9.68970499e-01, -2.72674681e+01],
       [-2.01058684e+01,  1.30806211e+03,  1.09750776e+02,
         7.40715787e+02,  1.33471810e+04,  1.31763772e+02,
         6.60843012e+00, -3.26425305e+01],
       [ 8.61911611e-01,  4.90694235e+01,  3.54084801e+01,
         4.51210934e+01,  1.31763772e+02,  5.83963085e+01,
         3.86740053e-01,  7.44076368e-01],
       [-2.02742736e-02,  1.971784

In [6]:
bgda.compute_covariance(X_train.values, y_train.values)

array([[ 5.15123191e+00,  2.00875667e+00,  4.03062241e+00,
        -1.87662120e+00, -1.52936465e+01, -3.67253194e-01,
        -2.67511154e-02,  9.29966025e+00],
       [ 2.00875667e+00,  4.00616490e+02,  3.35245147e+01,
        -1.81437453e+00,  5.27249899e+02,  5.22476848e+00,
         5.83973884e-01,  2.48265571e+01],
       [ 4.03062241e+00,  3.35245147e+01,  1.59501781e+02,
         2.12746109e+01,  3.73081089e+01,  1.50285808e+01,
         1.05499025e-01,  2.29198740e+01],
       [-1.87662120e+00, -1.81437453e+00,  2.12746109e+01,
         1.19463798e+02,  3.62648423e+02,  2.13863230e+01,
         4.60044875e-01, -1.52025494e+01],
       [-1.52936465e+01,  5.27249899e+02,  3.73081089e+01,
         3.62648423e+02,  6.54173496e+03,  4.57990652e+01,
         2.88620980e+00, -4.31528128e+01],
       [-3.67253194e-01,  5.22476848e+00,  1.50285808e+01,
         2.13863230e+01,  4.57990652e+01,  2.61393547e+01,
         1.29703957e-01, -3.71465486e+00],
       [-2.67511154e-02,  5.839738

### Heart Disease data set from Kaggle: https://www.kaggle.com/uciml/pima-indians-diabetes-database/data

In [7]:
bgda = BinaryGDA()
bgda.fit(X_train, y_train)
c = bgda.compute_covariance(X_train.values, y_train.values)
np.linalg.inv(c)
#bgda.print_params()

array([[ 2.66773725e-01,  4.78383599e-04, -9.83036189e-04,
        -2.16791633e-03,  4.04047531e-04, -9.14193784e-04,
         1.21284721e-01, -3.93769517e-02],
       [ 4.78383599e-04,  3.03636310e-03, -4.92542145e-04,
         1.12373469e-03, -2.94901604e-04, -7.59369907e-04,
        -2.23621457e-02, -1.05990087e-03],
       [-9.83036189e-04, -4.92542145e-04,  7.28489227e-03,
        -1.26120999e-03,  7.01888525e-05, -3.61826852e-03,
         5.96508489e-03, -2.77128654e-03],
       [-2.16791633e-03,  1.12373469e-03, -1.26120999e-03,
         1.26522185e-02, -6.91528038e-04, -8.03136403e-03,
        -5.89876457e-02,  2.43379838e-03],
       [ 4.04047531e-04, -2.94901604e-04,  7.01888525e-05,
        -6.91528038e-04,  2.15285601e-04,  2.30114720e-04,
        -2.76051666e-03,  2.51156970e-05],
       [-9.14193784e-04, -7.59369907e-04, -3.61826852e-03,
        -8.03136403e-03,  2.30114720e-04,  4.72334354e-02,
        -4.02446556e-02,  2.74590607e-03],
       [ 1.21284721e-01, -2.236214

In [8]:
bgda.class_conditional_p(1, X_train.iloc[0])

AttributeError: 'BinaryGDA' object has no attribute 'covariance'

In [ ]:
diabetes.head()

In [ ]:
plt.hist(diabetes.SkinThickness)
plt.show()